namespace UnitTests
{
    using NumbersToWords.NumbersConversion;
    using NUnit.Framework;

    [TestFixture]
    public class NumbersConverterTests
    {
        [TestCase(10ul, "М", "П", ExpectedResult = "десяти")]
        [TestCase(10ul, "м", "п", ExpectedResult = "десяти")]
        [TestCase(0ul, "М", "Д", ExpectedResult = "нолю")]
        [TestCase(1ul, "М", "И", ExpectedResult = "один")]
        [TestCase(1ul, "М", "Р", ExpectedResult = "одного")]
        [TestCase(1ul, "М", "Д", ExpectedResult = "одному")]
        [TestCase(1ul, "М", "В", ExpectedResult = "один")]
        [TestCase(1ul, "М", "Т", ExpectedResult = "одним")]
        [TestCase(1ul, "М", "П", ExpectedResult = "одном")]
        [TestCase(1ul, "Ж", "И", ExpectedResult = "одна")]
        [TestCase(1ul, "Ж", "Р", ExpectedResult = "одной")]
        [TestCase(1ul, "Ж", "Д", ExpectedResult = "одной")]
        [TestCase(1ul, "Ж", "В", ExpectedResult = "одну")]
        [TestCase(1ul, "Ж", "Т", ExpectedResult = "одной")]
        [TestCase(1ul, "Ж", "П", ExpectedResult = "одной")]
        [TestCase(1ul, "С", "И", ExpectedResult = "одно")]
        [TestCase(1ul, "С", "Р", ExpectedResult = "одного")]
        [TestCase(1ul, "С", "Д", ExpectedResult = "одному")]
        [TestCase(1ul, "С", "В", ExpectedResult = "одно")]
        [TestCase(1ul, "С", "Т", ExpectedResult = "одним")]
        [TestCase(1ul, "С", "П", ExpectedResult = "одном")]
        [TestCase(2ul, "М", "И", ExpectedResult = "два")]
        [TestCase(2ul, "Ж", "И", ExpectedResult = "две")]
        [TestCase(2ul, "С", "И", ExpectedResult = "два")]
        [TestCase(3ul, "М", "И", ExpectedResult = "три")]
        [TestCase(3ul, "Ж", "И", ExpectedResult = "три")]
        [TestCase(3ul, "С", "И", ExpectedResult = "три")]
        [TestCase(19ul, "М", "Т", ExpectedResult = "девятнадцатью")]
        [TestCase(20ul, "М", "Т", ExpectedResult = "двадцатью")]
        [TestCase(21ul, "М", "Т", ExpectedResult = "двадцатью одним")]
        [TestCase(100ul, "М", "Т", ExpectedResult = "ста")]
        [TestCase(101ul, "М", "Т", ExpectedResult = "ста одним")]
        [TestCase(120ul, "М", "Т", ExpectedResult = "ста двадцатью")]
        [TestCase(121ul, "М", "Т", ExpectedResult = "ста двадцатью одним")]
        [TestCase(1000ul, "М", "И", ExpectedResult = "одна тысяча")]
        [TestCase(1000ul, "М", "Р", ExpectedResult = "одной тысячи")]
        [TestCase(1000ul, "М", "Д", ExpectedResult = "одной тысяче")]
        [TestCase(1000ul, "М", "В", ExpectedResult = "одну тысячу")]
        [TestCase(1000ul, "М", "Т", ExpectedResult = "одной тысячей")]
        [TestCase(1000ul, "М", "П", ExpectedResult = "одной тысяче")]
        [TestCase(2000ul, "М", "И", ExpectedResult = "две тысячи")]
        [TestCase(2000ul, "М", "Р", ExpectedResult = "двух тысяч")]
        [TestCase(2000ul, "М", "Д", ExpectedResult = "двум тысячам")]
        [TestCase(2000ul, "М", "В", ExpectedResult = "две тысячи")]
        [TestCase(2000ul, "М", "Т", ExpectedResult = "двумя тысячами")]
        [TestCase(2000ul, "М", "П", ExpectedResult = "двух тысячах")]
        [TestCase(5000ul, "М", "И", ExpectedResult = "пять тысяч")]
        [TestCase(5000ul, "М", "Р", ExpectedResult = "пяти тысяч")]
        [TestCase(5000ul, "М", "Д", ExpectedResult = "пяти тысячам")]
        [TestCase(5000ul, "М", "В", ExpectedResult = "пять тысяч")]
        [TestCase(5000ul, "М", "Т", ExpectedResult = "пятью тысячами")]
        [TestCase(5000ul, "М", "П", ExpectedResult = "пяти тысячах")]
        [TestCase(20000ul, "М", "И", ExpectedResult = "двадцать тысяч")]
        [TestCase(21000ul, "М", "И", ExpectedResult = "двадцать одна тысяча")]
        [TestCase(121121ul, "М", "Т", ExpectedResult = "ста двадцатью одной тысячей ста двадцатью одним")]
        [TestCase(1000000ul, "М", "И", ExpectedResult = "один миллион")]
        [TestCase(1000000ul, "М", "Р", ExpectedResult = "одного миллиона")]
        [TestCase(1000000ul, "М", "Д", ExpectedResult = "одному миллиону")]
        [TestCase(1000000ul, "М", "В", ExpectedResult = "один миллион")]
        [TestCase(1000000ul, "М", "Т", ExpectedResult = "одним миллионом")]
        [TestCase(1000000ul, "М", "П", ExpectedResult = "одном миллионе")]
        [TestCase(2000000ul, "М", "И", ExpectedResult = "два миллиона")]
        [TestCase(2000000ul, "М", "Р", ExpectedResult = "двух миллионов")]
        [TestCase(2000000ul, "М", "Д", ExpectedResult = "двум миллионам")]
        [TestCase(2000000ul, "М", "В", ExpectedResult = "два миллиона")]
        [TestCase(2000000ul, "М", "Т", ExpectedResult = "двумя миллионами")]
        [TestCase(2000000ul, "М", "П", ExpectedResult = "двух миллионах")]
        [TestCase(5000000ul, "М", "И", ExpectedResult = "пять миллионов")]
        [TestCase(5000000ul, "М", "Р", ExpectedResult = "пяти миллионов")]
        [TestCase(5000000ul, "М", "Д", ExpectedResult = "пяти миллионам")]
        [TestCase(5000000ul, "М", "В", ExpectedResult = "пять миллионов")]
        [TestCase(5000000ul, "М", "Т", ExpectedResult = "пятью миллионами")]
        [TestCase(5000000ul, "М", "П", ExpectedResult = "пяти миллионах")]
        [TestCase(20000000ul, "М", "И", ExpectedResult = "двадцать миллионов")]
        [TestCase(21000000ul, "М", "И", ExpectedResult = "двадцать один миллион")]
        [TestCase(121121121ul, "М", "Т", ExpectedResult = "ста двадцатью одним миллионом ста двадцатью одной тысячей ста двадцатью одним")]
        [TestCase(1000000000ul, "М", "И", ExpectedResult = "один миллиард")]
        [TestCase(2000000000ul, "М", "И", ExpectedResult = "два миллиарда")]
        [TestCase(5000000000ul, "М", "И", ExpectedResult = "пять миллиардов")]
        [TestCase(20000000000ul, "М", "И", ExpectedResult = "двадцать миллиардов")]
        [TestCase(21000000000ul, "М", "И", ExpectedResult = "двадцать один миллиард")]
        [TestCase(121121121121ul, "М", "Т", ExpectedResult = "ста двадцатью одним миллиардом ста двадцатью одним миллионом ста двадцатью одной тысячей ста двадцатью одним")]
        [TestCase(31ul, "М", "Р", ExpectedResult = "тридцати одного")]
        [TestCase(22ul, "С", "Т", ExpectedResult = "двадцатью двумя")]
        [TestCase(154323ul, "М", "И", ExpectedResult = "сто пятьдесят четыре тысячи триста двадцать три")]
        [TestCase(154323ul, "М", "Т", ExpectedResult = "ста пятьюдесятью четырьмя тысячами тремястами двадцатью тремя")]
        public string SumPropTest(ulong nSum, string sGender, string sCase)
        {
            var converter = new NumbersConverter();

            return converter.SumProp(nSum, sGender, sCase);
        }
    }
}
